export const types = {
	REQUEST_CONFIGURATION_LOADING: "REQUEST_CONFIGURATION_LOADING",
	REQUEST_CONFIGURATION_SUCCESS: "REQUEST_CONFIGURATION_SUCCESS",
	REQUEST_CONFIGURATION_FAILURE: "REQUEST_CONFIGURATION_FAILURE",
	OPEN_SIDEBAR: "OPEN_SIDEBAR",
};
